source 'https://rubygems.org'

gem 'rake'
gem 'librarian-puppet'
gem 'metadata-json-lint'
gem 'puppet', ENV['PUPPET_VERSION'] || '~> 3.7.0'
gem 'puppet-lint'
gem 'puppet-syntax'
gem 'puppetlabs_spec_helper'
gem 'rspec-puppet', :git => 'https://github.com/rodjek/rspec-puppet.git'
