source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'rake'
gem 'librarian-puppet'
gem 'metadata-json-lint'
gem 'puppet', ENV['PUPPET_VERSION'] || '~> 6.4.0'
gem 'puppet-lint'
gem 'puppet-syntax'
gem 'puppetlabs_spec_helper'
gem 'rspec-puppet'
