name    'jdowning/rbenv'
version '0.1.0'
source 'https://github.com/justindowning/puppet-rbenv'
author 'Justin Donwing'
license 'Apache License, Version 2.0'
summary 'Install rbenv on Ubuntu'
description 'Setup rbenv for ruby management on Ubuntu'
project_page 'https://github.com/justindowning/puppet-rbenv'
